#!/bin/bash
usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
EOF
	exit
}

cmd=$1
case $cmd in
	'xping')
		cd
		title xping
		sudo ~/bin/xping
		;;
	'eclipse')
		cd
		title eclipse
		eclipse
		;;
	'yping')
		cd
		title yping
		for x in `ps aux | grep eth0 | sed 's/\s\s*/ /g' | cut -d ' ' -f 2`; do sudo kill -9 $x; done
		;;
	'zping')
		cd
		title zping
		ping -i5 tw.yahoo.com
		;;
	'mongoose')
		#cd
		title mongoose
		mongoose
		;;
	'4'|'wrk1')
		xcd app
		cd prj/einopad/assets/www
		title wrk1
		;;
	'5'|'wrk2')
		xcd app
		cd prj/einopad/assets/www
		title wrk2
		;;
	'6'|'wrk3')
		xcd app
		cd prj/einopad/assets/www
		title wrk3
		;;
	*)
		echo "Unknown option '$cmd'!"
		usage
esac
