#!/bin/sh
usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
EOF
	exit
}

OS=$(uname)
case $OS in
	'Darwin')
		OS='osx'
		;;
	'Linux')
		OS='linux'
		;;
	*)
		echo "Unknown OS!"
		usage
esac


do_osx(){
	while :; do
		brew update && brew upgrade
		break
	done
}

do_linux(){
	while :; do
		_=$(which apt)
		if [ 0 -eq $? ]; then
			sudo apt update
			sudo apt -y upgrade
			sudo apt -y autoremove
			break
		fi

		_=$(which apt-get)
		if [ 0 -eq $? ]; then
			sudo apt-get update
			sudo apt-get dist-upgrade
			break
		fi

		dmesg | head -9 | grep -i 'red hat' > /dev/null
		if [ 0 -eq $? ]; then
			sudo yum -y update
			break
		fi

		# quit
		echo "unknow distro! abort."
		break
	done
}

# common of OSs
do_$OS
