#!/bin/sh
cd $1
git remote add origin https://song10@bitbucket.org/song10/${1}.git
git push -u origin --all # pushes up the repo and its refs for the first time
git push -u origin --tags # pushes up any tags
