#!/bin/sh
if test 1 -gt $#; then
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  exit $?
fi

sudo cpufreq-selector -g $* 
