#!/bin/sh
ins=""
_=$(which cpufreq-info) || ins="$ins cpufrequtils"
_=$(which cpufreq-selector) || ins="$ins gnome-applets"
if test '0' != `echo $ins|wc -w`; then
	sudo apt-get install -y $ins
fi

if test 1 -gt $#; then
  cpufreq-info
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  exit $?
fi

echo sudo cpufreq-selector -g $* \&
sudo cpufreq-selector -g $* &
