#!/bin/sh
usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
EOF
	exit
}

OS=$(uname)
case $OS in
	'Darwin')
		OS='osx'
		;;
	'Linux')
		OS='linux'
		;;
	*)
		echo "Unknown OS!"
		usage
esac


do_osx(){
	if [ 'up' = "$1" ]; then
		shift
		sudo echo -n # to ask sudo password first
		gitup
		aptup
		sudo softwareupdate -i -a
	else
		gitup
	fi
}

do_linux(){
	if [ 'up' = "$1" ]; then
		shift
		sudo echo -n # to ask sudo password first
		gitup
		aptup
	else
		gitup
	fi
}

# main()
OPT_ALARM=false
OPT_FORCE=false
OPT_UPDATE=false

while getopts ":afu" opt; do
  case $opt in
    a)
      # echo "-a" >&2
      OPT_ALARM=true
      ;;
    f)
      # echo "-f" >&2
      OPT_FORCE=true
      ;;
    u)
      # echo "-u" >&2
      OPT_UPDATE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

# common among OSs
title
payrolltime && $postcmdtit

if $OPT_FORCE; then
	echo "Forced is nothing!"
fi

if $OPT_ALARM; then
	xalarm -q -s -t "17:15" "$HOSTNAME: Ready to Home, Rex."
	xalarm -q -s -t "17:30" "$HOSTNAME: Rex, Go Home Now!"
fi

if $OPT_UPDATE; then
	do_$OS $*
fi
