#!/bin/sh
usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
EOF
	exit
}

OS=$(uname)
case $OS in
	'Darwin')
		OS='osx'
		;;
	'Linux')
		OS='linux'
		;;
	*)
		echo "Unknown OS!"
		usage
esac


do_osx(){
	if [ 'up' = "$1" ]; then
		shift
		sudo echo -n # to ask sudo password first
		gitup
		aptup
		sudo softwareupdate -i -a
	else
		gitup
	fi
}

do_linux(){
	if [ 'up' = "$1" ]; then
		shift
		sudo echo -n # to ask sudo password first
		gitup
		aptup
	else
		gitup
	fi
}

# common of OSs
title

if [ '-f' = "$1" ]; then
	shift;
	postcmd=':'
else
	postcmd='exit'
fi
payrolltime && $postcmd
if [ 2 = $? ]; then opt='-a -f'; fi

if [ 'is1171' = `hostname` ]; then
	xalarm -q -s -a "8:50" "Ready to Home, Rex."
	xalarm -q -s -a "9:00" "Rex, Go Home Now!"
fi

do_$OS $*
exit $?
