#!/bin/sh

usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
		-h print usage
		-a do aptup
		-f force
		-u do update
		-A do alarm
EOF
	exit
}

OS=$(uname)
case $OS in
	'Darwin')
		OS='osx'
		;;
	'Linux')
		OS='linux'
		;;
	*)
		echo "Unknown OS!"
		usage
esac


do_aptup_osx(){
	sudo echo -n # to ask sudo password first
	aptup
	sudo softwareupdate -i -a
}

do_aptup_linux(){
	sudo echo -n # to ask sudo password first
	aptup
}

# main()
OPT_ALARM=false
OPT_FORCE=false
OPT_UPDATE=false
OPT_APTUP=false

while getopts ":hafuA" opt; do
	case $opt in
		a)
			# echo "-a" >&2
			OPT_APTUP=true
			sudo echo
			;;
		f)
			# echo "-f" >&2
			OPT_FORCE=true
			;;
		u)
			# echo "-u" >&2
			OPT_UPDATE=true
			;;
		A)
			# echo "-a" >&2
			OPT_ALARM=true
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
		h)
			usage
			;;
	esac
done

# common among OSs
title
payrolltime && $postcmdtit

if $OPT_FORCE; then
	echo "Forced is nothing!"
fi

if $OPT_ALARM; then
	xalarm -q -s -t "17:15" "$HOSTNAME: Ready to Home, Rex."
	xalarm -q -s -t "17:30" "$HOSTNAME: Rex, Go Home Now!"
fi

if $OPT_UPDATE; then
		gitup
fi

if $OPT_APTUP; then
	do_aptup_$OS
fi
