#!/bin/sh

npmcmd=install
npmmod="\
 coffee-script\
 js2coffee\
 nopt\
 dot\
 express@2\
 jade\
 less\
 html2jade\
 markdown\
 jslint\
 jquery\
 connect\
 dnode\
"
_=`which curl` \
	|| sudo apt-get install -y curl

_=`which npm` \
	|| curl http://npmjs.org/install.sh | npm_config_prefix=$HOME/opt sh

expr "$*" : '.* \?debug \?' > /dev/null && \
 npmflags="$npmflags -ddd"

expr "$*" : '.* \?remove \?' > /dev/null && \
 npmcmd=remove && npmmod="$npmmod npm"

_npm () {
	echo
	echo "npm $npmcmd -g $npmflags $1"
	npm $npmcmd -g $npmflags $1
}

for x in $npmmod; do
	_npm $x
done
