#!/bin/sh

R=$(readlink -f $(dirname $0)/../wrk)
cd $R

expr "$*" : '.* \?-i \?' > /dev/null && \
  sudo apt-get install -y vim git mercurial exuberant-ctags links curl splint tidy pyflakes pylint chktex libxml2-utils ruby-dev \
  #npm install -g jslint

expr "$*" : '.* \?-f \?' > /dev/null && \
  force=yes

T='pct.vim'
build=yes
if [ -d $T/ ]; then
  cd $T
  git reset --hard
  x=`git pul`
  echo ===
  echo $x
  echo ===
  expr "$x" : "Current.*up to date" > /dev/null && \
    build=no && if test "yes" != "$force"; then echo no build; fi
else
  git clone https://github.com/pct/pct.vim.git
  cd $T/
fi

if [ ! -e ~/.vimrc.yours ]; then
  mv ~/.vimrc ~/.vimrc.yours
  mv ~/.vim ~/.vim.yours
fi

./update.sh
cd .vim/bundle/Command-T/ruby/command-t/; ruby extconf.rb; make; sudo make install; cd -
ln -s -f `pwd`/.vimrc ~/
ln -s -f `pwd`/.vim ~/

# patch
#sed -i '/echo.\+"withdrawn"/ d' ~/.vim/bundle/man-page-view/plugin/withdrawn.vim
echo 'set nobackup' >> ~/.vimrc
echo 'set ts=4' >> ~/.vimrc
echo 'set noexpandtab' >> ~/.vimrc
echo '" highlight tabs and trailing spaces' >> ~/.vimrc
echo 'set listchars=tab:>-,trail:-' >> ~/.vimrc
echo 'set nolist' >> ~/.vimrc
echo 'set mouse=' >> ~/.vimrc
echo 'highlight LineNr ctermfg=blue' >> ~/.vimrc
echo 'set foldmethod=expr' >> ~/.vimrc
echo 'set foldcolumn=0' >> ~/.vimrc

patch -N -r - ~/wrk/pct.vim/.vim/bundle/neocomplcache/plugin/neocomplcache.vim ~/bin/patch/vim-000.patch 2>&1 > /dev/null
