#!/usr/bin/env bash

set -euo pipefail

read lport uport < /proc/sys/net/ipv4/ip_local_port_range
while true; do
    port=$(shuf -i "$lport-$uport" -n1)
    nc -z 127.0.0.1 "$port" || break
done

ssh -M -S "/tmp/git-proxy-$port" -o ExitOnForwardFailure=yes -NfTL "${port}:$1:$2" atcsqa06 1>&2
trap "ssh -q -S /tmp/git-proxy-$port -O exit atcsqa06" EXIT
socat STDIO TCP:localhost:$port
