#!/bin/sh

# $0 [-n] [files]

args="--assume-unchanged"
grepopt="-P"
uname -a | grep -i darwin 2>&1 >/dev/null && grepopt="-G"

if test 0 -lt $#; then
	opt=$1
	shift
	case $opt in
		-n) args="$args --no-assume-unchanged";;
		-a) args2=" | tee -a .gitignore";;
	esac
fi

if test 0 -lt $#; then
	git update-index $args $*
else
	if [ -z "$args2" ]; then
		git st | grep $grepopt '^#\t' | sed 's/#	//' | grep -v $grepopt '^\.\.'
	else
		git st | grep $grepopt '^#\t' | sed 's/#	//' | grep -v $grepopt '^\.\.' | tee -a .gitignore
	fi
fi
