#!/bin/sh

PRJS="https://github.com/song10/ubfavor.git|$HOME/wrk/ubfavor https://github.com/song10/bin.git|$HOME/bin $HOME/Dropbox/repo/my/xman.git|$HOME/wrk/xman"
HERE=`pwd`

_status () {
	PS="$HOME $HOME/bin $HOME/wrk/ubfavor $HOME/wrk/xman"
	for x in $PS; do
		echo
		cd $x
		pwd
		git status
	done
	x=$?
	cd $HERE
	return $x
}

if test "st" = "$1"; then
	status
	exit $?
fi

cmd="gituphere https://github.com/song10/ubhome.git"
echo $cmd
cd $HOME && $cmd
cd $HERE

for x in $PRJS; do
	gn=$(echo $x|cut -d'|' -f1)
	pa=$(echo $x|cut -d'|' -f2)
	cmd="gitupx $gn $pa"
	echo $cmd
	$cmd
done

_status
