#!/bin/sh

if test $# -lt 1 ; then
	echo need 1 argument;
	exit 1;
fi

_gituphere () {
	GIT=$1
	if [ ! -d ".git" ]; then
		git init
		git remote add origin "$GIT"
		git fetch
		git checkout -b master origin/master
	else
		_=$(git status|grep Changes) && x=true || x=false
		if $x; then _=$(git stash); fi
		git pull --rebase
		if $x; then _=$(git stash pop); fi
	fi
}

if [ ! `which git` ]; then
	sudo apt-get install -y git
fi

_gituphere $*
