#!/bin/sh

if test $# -lt 2 ; then
	echo need 2 arguments;
	exit 1;
fi

_gitup () {
	GIT=$1
	DIR=$2
	if [ ! -d "$DIR" ]; then
		git clone "$GIT" "$DIR"
	else
		cd "$DIR"
		_=$(git status|grep Changes) && x=true || x=false
		if $x; then _=$(git stash); fi
		git pull --rebase
		if $x; then _=$(git stash pop); fi
	fi
}

if [ -n "$ROOT" ]; then
	cd $ROOT
fi

_gitup $*
