#!/bin/sh

# coffee-script
SUDO=
DIR="$HOME/.local/share/gtksourceview-3.0/language-specs $HOME/.local/share/gtksourceview-2.0/language-specs /usr/share/gtksourceview-3.0/language-specs /usr/share/gtksourceview-2.0/language-specs"
for x in $DIR; do
	if [ -d $x ]; then
	  DIR=$x;
	  break;
	fi
done
case $DIR in
    /usr/* ) SUDO=sudo ;;
esac
NAME=coffee_script.lang
echo "$SUDO wget -O $DIR/$NAME"
if [ ! -e $DIR/$NAME ]; then
  $SUDO wget -O$DIR/$NAME https://raw.github.com/wavded/gedit-coffeescript/master/$NAME
fi

# show white-space (not working)
if false; then
mkdir -p ~/.local/share/gedit/plugins
SUDO=
DIR="$HOME/.local/share/gedit/plugins /usr/lib/gedit/plugins"
for x in $DIR; do
	if [ -d $x ]; then
	  DIR=$x;
	  break;
	fi
done
echo $DIR
case $DIR in
    /usr/* ) SUDO=sudo ;;
esac
NAME=whitespace.plugin
$SUDO wget -O$DIR/$NAME https://raw.github.com/yordan94/gedit-3-whitespace/master/$NAME
NAME=whitespace.py
$SUDO wget -O$DIR/$NAME https://raw.github.com/yordan94/gedit-3-whitespace/master/$NAME
fi
