#!/bin/sh
which pandoc > /dev/null
if [ 0 -ne $? ]; then
  sudo apt-get -y install pandoc
fi

for x in $*; do
  echo "pandoc -f markdown -s -S -t mediawiki -o $x.mw $x"
  pandoc -f markdown -s -S -t mediawiki -o $x.mw $x
done
