#!/bin/sh
gets='ninja node'
if [ '-a' = "$1" ]; then
  gets="$gets ringojs perl6"
  shift
fi
for x in $gets; do
	echo "myget $x $*"
	myget $x $*
done

for x in $gets; do
  if [ "ringojs" = "$x" ]; then x='ringo'; fi
  echo "$x:" $($x --version)
done
