#!/usr/bin/env perl
use strict;
#
# get last login time
#
my $exit = 0; # not the first time per day
my $last = `tail -n1 ~/.payrolltime 2>/dev/null`;
#chomp $last;
$last =~ m/^(\S+) (\S+)/;
my ($ldate, $ltime) = ($1, $2);
#print "$ldate, $ltime\n";
#
# get currnet time
#
my $now = `date '+%Y-%m-%d %H:%M'`;
$now =~ m/^(\S+) (\S+)/;
my ($ndate, $ntime) = ($1, $2);
#print "$ndate, $ntime\n";
#
# log currnet time if necessary, and count result
#
if ($ndate ne $ldate) {
  `echo -n '$now' >> ~/.payrolltime`;
  $exit = 1; # the first time per day
  if ((substr $ndate, 0, 7) ne (substr $ldate, 0, 7)) {
    $exit = 2; # the first time per month
  }
}

system('tail -n1 ~/.payrolltime');
exit $exit
