#!/usr/bin/env perl
use strict;
my $last = `tail -n1 ~/.payrolltime 2>/dev/null`;
#chomp $last;
$last =~ m/^(\S+) (\S+)/;
my ($ldate, $ltime) = ($1, $2);
#print "$ldate, $ltime\n";
my $now = `date '+%Y-%m-%d %H:%M'`;
$now =~ m/^(\S+) (\S+)/;
my ($ndate, $ntime) = ($1, $2);
#print "$ndate, $ntime\n";
if ($ndate ne $ldate) {
  `date '+%Y-%m-%d %H:%M' >> ~/.payrolltime`;
}

system('tail -n1 ~/.payrolltime');
