#!/bin/bash

usage(){
	cat <<EOF
Usage:
	`basename $0` [options]
		-h print usage
		-v print verbose messages
		-t test version toolchain
		-3 bsp3 toolchain
		-4 bsp4 toolchain
EOF
	exit
}

if [ $# -eq 0 ]; then usage; fi

LD_VER=t
LIBPATH="/home/data/andes/toolchain/v3/ins/nds32le-linux"

opt_verbose=false

OPTIND=1
while getopts ":hv43t" opt; do
	case $opt in
		t)
			LD_VER=t
			LIBPATH="/home/data/andes/toolchain/v3/ins/nds32le-linux"
			shift $((OPTIND-1))
			;;
		3)
			LD_VER=3
			LIBPATH="/home/song10/my/andes/bsp/bsp321/nds32le-linux-glibc-v3/nds32le-linux/libc"
			shift $((OPTIND-1))
			;;
		4)
			LD_VER=4
			LIBPATH="~/my/andes/glibc/bsp410/build_glibc_test_for_REX/local"
			shift $((OPTIND-1))
			;;
		v)
			opt_verbose=true
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
	esac
done

QEMU=~/my/andes/qemu/ins.qemu.nds/bin/qemu-nds32
QEMUFLAGS="-L ${LIBPATH} -E LD_LIBRARY_PATH=."

if ${opt_verbose}; then
	echo "${QEMU} ${QEMUFLAGS} $@"
fi

${QEMU} ${QEMUFLAGS} $@
