#!/bin/sh

if { [ ! 'screen' = "$TERM" ] && [ -z "$STY" ]; } then
	TYPE='tab'
else
	TYPE='scr'
fi
#echo "TYPE=$TYPE"

case $1 in
	"tab")
		TYPE='tab'
		shift
		;;
	"scr")
		TYPE='scr'
		shift
		;;
	"all")
		TYPE='tab scr'
		shift
		;;
	*)
		:
	;;
esac

if [ 0 -lt $# ];then
	TITLE="$1"
	shift
else
	TITLE=`hostname`
fi

CDIR=`pwd`
case $TITLE in
	".")
		TITLE=$(basename ${CDIR})
		;;
	"..")
		_TMP=$(dirname ${CDIR})
		TITLE=$(basename ${CDIR})
		TITLE="$(basename ${_TMP})/${TITLE}"
		;;
	*)
		:
	;;
esac

# echo "set '$TYPE' title: '$TITLE'"

for x in $TYPE; do
	case $x in
		"tab")
			printf "\033]2;$TITLE\007"
			;;
		"scr")
			printf '\033k'$TITLE'\033\\'
			;;
		*)
			:
		;;
	esac
done
