#!/bin/sh

if [ -z "$STY" ]; then
	TYPE='tab'
else
	TYPE='scr'
fi

case $1 in
	"tab")
		TYPE='tab'
		shift
		;;
	"scr")
		TYPE='scr'
		shift
		;;
	"all")
		TYPE='tab scr'
		shift
		;;
	*)
		:
	;;
esac

TITLE="$1"
shift
if [ -z "$TITLE" ]; then TITLE=`hostname`; fi

case $TITLE in
	".")
		TITLE=$(basename $(pwd))
		;;
	*)
		:
	;;
esac

# echo "set '$TYPE' title: '$TITLE'"

for x in $TYPE; do
	case $x in
		"tab")
			printf "\033]2;$TITLE\007"
			;;
		"scr")
			printf '\033k'$TITLE'\033\\'
			;;
		*)
			:
		;;
	esac
done
