#!/usr/bin/perl
if (1 > @ARGV) { print "no file to edit\n"; exit; }

my $arg = join(' ', @ARGV);
my ($fn, $ln);
while (1) {
	$ln = 1;
	@words = split ':| +', $arg;

	# xxx:yyy...:ddd
	if (2 < @words and $words[$#words] =~ m|(\d+)|) {
		($fn,$ln)=($words[0],$1);
		# ...:35:18:
		my $char = substr $arg, -1;
		if (':' == $char and $words[$#words-1] =~ m|(\d+)|) {
				$ln = $1;
		}
		last;
	}

	# xxx:ddd
	if (1 < @words and $words[1] =~ m|(\d+)|) {
		($fn,$ln)=($words[0],$1);
		last;
	}

	$fn=$ARGV[0];
	last;
}

$ln="+$ln";

`which vim`;
if ($?) {
	`sudo apt-get -y install vim`;
}

if (defined($ENV{'MyVerbose'})) {
	print "fn: '$fn'\n";
	print "ln: '$ln'\n";
}

system("vim $fn $ln");

if (0) {
	my $hostname = `hostname`;
	chomp $hostname;
	my $cmdln = "echo -ne '\\033]2;$hostname\\007'";
	print "$cmdln\n";
	system($cmdln);
}
