#!/bin/sh

case $1 in
	"-0")
		ps aux | grep auth
		exit
		;;
	"-1")
		opt="$opt -once"
		shift
		;;
	"-9")
		shift
		;;
	*)
		:
		;;
esac

which x11vnc || sudo apt-get install -y x11vnc

sudo x11vnc -safer $opt -nopw -auth /var/run/lightdm/root/:0 -display :0 $*
